# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/carlos/workspace/work/cryptography

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/carlos/workspace/work/cryptography

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlos/workspace/work/cryptography/CMakeFiles /Users/carlos/workspace/work/cryptography//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carlos/workspace/work/cryptography/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypto_test_entry.elf

# Build rule for target.
crypto_test_entry.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto_test_entry.elf
.PHONY : crypto_test_entry.elf

# fast build rule for target.
crypto_test_entry.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/build
.PHONY : crypto_test_entry.elf/fast

lib/kasumi/f8.o: lib/kasumi/f8.c.o
.PHONY : lib/kasumi/f8.o

# target to build an object file
lib/kasumi/f8.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f8.c.o
.PHONY : lib/kasumi/f8.c.o

lib/kasumi/f8.i: lib/kasumi/f8.c.i
.PHONY : lib/kasumi/f8.i

# target to preprocess a source file
lib/kasumi/f8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f8.c.i
.PHONY : lib/kasumi/f8.c.i

lib/kasumi/f8.s: lib/kasumi/f8.c.s
.PHONY : lib/kasumi/f8.s

# target to generate assembly for a file
lib/kasumi/f8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f8.c.s
.PHONY : lib/kasumi/f8.c.s

lib/kasumi/f9.o: lib/kasumi/f9.c.o
.PHONY : lib/kasumi/f9.o

# target to build an object file
lib/kasumi/f9.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f9.c.o
.PHONY : lib/kasumi/f9.c.o

lib/kasumi/f9.i: lib/kasumi/f9.c.i
.PHONY : lib/kasumi/f9.i

# target to preprocess a source file
lib/kasumi/f9.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f9.c.i
.PHONY : lib/kasumi/f9.c.i

lib/kasumi/f9.s: lib/kasumi/f9.c.s
.PHONY : lib/kasumi/f9.s

# target to generate assembly for a file
lib/kasumi/f9.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/f9.c.s
.PHONY : lib/kasumi/f9.c.s

lib/kasumi/kasumi.o: lib/kasumi/kasumi.c.o
.PHONY : lib/kasumi/kasumi.o

# target to build an object file
lib/kasumi/kasumi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/kasumi.c.o
.PHONY : lib/kasumi/kasumi.c.o

lib/kasumi/kasumi.i: lib/kasumi/kasumi.c.i
.PHONY : lib/kasumi/kasumi.i

# target to preprocess a source file
lib/kasumi/kasumi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/kasumi.c.i
.PHONY : lib/kasumi/kasumi.c.i

lib/kasumi/kasumi.s: lib/kasumi/kasumi.c.s
.PHONY : lib/kasumi/kasumi.s

# target to generate assembly for a file
lib/kasumi/kasumi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/kasumi.c.s
.PHONY : lib/kasumi/kasumi.c.s

lib/kasumi/test_kasumi.o: lib/kasumi/test_kasumi.c.o
.PHONY : lib/kasumi/test_kasumi.o

# target to build an object file
lib/kasumi/test_kasumi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/test_kasumi.c.o
.PHONY : lib/kasumi/test_kasumi.c.o

lib/kasumi/test_kasumi.i: lib/kasumi/test_kasumi.c.i
.PHONY : lib/kasumi/test_kasumi.i

# target to preprocess a source file
lib/kasumi/test_kasumi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/test_kasumi.c.i
.PHONY : lib/kasumi/test_kasumi.c.i

lib/kasumi/test_kasumi.s: lib/kasumi/test_kasumi.c.s
.PHONY : lib/kasumi/test_kasumi.s

# target to generate assembly for a file
lib/kasumi/test_kasumi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/lib/kasumi/test_kasumi.c.s
.PHONY : lib/kasumi/test_kasumi.c.s

modules/asym/src/mbedtls_dh_client.o: modules/asym/src/mbedtls_dh_client.c.o
.PHONY : modules/asym/src/mbedtls_dh_client.o

# target to build an object file
modules/asym/src/mbedtls_dh_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_client.c.o
.PHONY : modules/asym/src/mbedtls_dh_client.c.o

modules/asym/src/mbedtls_dh_client.i: modules/asym/src/mbedtls_dh_client.c.i
.PHONY : modules/asym/src/mbedtls_dh_client.i

# target to preprocess a source file
modules/asym/src/mbedtls_dh_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_client.c.i
.PHONY : modules/asym/src/mbedtls_dh_client.c.i

modules/asym/src/mbedtls_dh_client.s: modules/asym/src/mbedtls_dh_client.c.s
.PHONY : modules/asym/src/mbedtls_dh_client.s

# target to generate assembly for a file
modules/asym/src/mbedtls_dh_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_client.c.s
.PHONY : modules/asym/src/mbedtls_dh_client.c.s

modules/asym/src/mbedtls_dh_server.o: modules/asym/src/mbedtls_dh_server.c.o
.PHONY : modules/asym/src/mbedtls_dh_server.o

# target to build an object file
modules/asym/src/mbedtls_dh_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_server.c.o
.PHONY : modules/asym/src/mbedtls_dh_server.c.o

modules/asym/src/mbedtls_dh_server.i: modules/asym/src/mbedtls_dh_server.c.i
.PHONY : modules/asym/src/mbedtls_dh_server.i

# target to preprocess a source file
modules/asym/src/mbedtls_dh_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_server.c.i
.PHONY : modules/asym/src/mbedtls_dh_server.c.i

modules/asym/src/mbedtls_dh_server.s: modules/asym/src/mbedtls_dh_server.c.s
.PHONY : modules/asym/src/mbedtls_dh_server.s

# target to generate assembly for a file
modules/asym/src/mbedtls_dh_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_dh_server.c.s
.PHONY : modules/asym/src/mbedtls_dh_server.c.s

modules/asym/src/mbedtls_ecc.o: modules/asym/src/mbedtls_ecc.c.o
.PHONY : modules/asym/src/mbedtls_ecc.o

# target to build an object file
modules/asym/src/mbedtls_ecc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecc.c.o
.PHONY : modules/asym/src/mbedtls_ecc.c.o

modules/asym/src/mbedtls_ecc.i: modules/asym/src/mbedtls_ecc.c.i
.PHONY : modules/asym/src/mbedtls_ecc.i

# target to preprocess a source file
modules/asym/src/mbedtls_ecc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecc.c.i
.PHONY : modules/asym/src/mbedtls_ecc.c.i

modules/asym/src/mbedtls_ecc.s: modules/asym/src/mbedtls_ecc.c.s
.PHONY : modules/asym/src/mbedtls_ecc.s

# target to generate assembly for a file
modules/asym/src/mbedtls_ecc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecc.c.s
.PHONY : modules/asym/src/mbedtls_ecc.c.s

modules/asym/src/mbedtls_ecdh_client.o: modules/asym/src/mbedtls_ecdh_client.c.o
.PHONY : modules/asym/src/mbedtls_ecdh_client.o

# target to build an object file
modules/asym/src/mbedtls_ecdh_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_client.c.o
.PHONY : modules/asym/src/mbedtls_ecdh_client.c.o

modules/asym/src/mbedtls_ecdh_client.i: modules/asym/src/mbedtls_ecdh_client.c.i
.PHONY : modules/asym/src/mbedtls_ecdh_client.i

# target to preprocess a source file
modules/asym/src/mbedtls_ecdh_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_client.c.i
.PHONY : modules/asym/src/mbedtls_ecdh_client.c.i

modules/asym/src/mbedtls_ecdh_client.s: modules/asym/src/mbedtls_ecdh_client.c.s
.PHONY : modules/asym/src/mbedtls_ecdh_client.s

# target to generate assembly for a file
modules/asym/src/mbedtls_ecdh_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_client.c.s
.PHONY : modules/asym/src/mbedtls_ecdh_client.c.s

modules/asym/src/mbedtls_ecdh_server.o: modules/asym/src/mbedtls_ecdh_server.c.o
.PHONY : modules/asym/src/mbedtls_ecdh_server.o

# target to build an object file
modules/asym/src/mbedtls_ecdh_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_server.c.o
.PHONY : modules/asym/src/mbedtls_ecdh_server.c.o

modules/asym/src/mbedtls_ecdh_server.i: modules/asym/src/mbedtls_ecdh_server.c.i
.PHONY : modules/asym/src/mbedtls_ecdh_server.i

# target to preprocess a source file
modules/asym/src/mbedtls_ecdh_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_server.c.i
.PHONY : modules/asym/src/mbedtls_ecdh_server.c.i

modules/asym/src/mbedtls_ecdh_server.s: modules/asym/src/mbedtls_ecdh_server.c.s
.PHONY : modules/asym/src/mbedtls_ecdh_server.s

# target to generate assembly for a file
modules/asym/src/mbedtls_ecdh_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_ecdh_server.c.s
.PHONY : modules/asym/src/mbedtls_ecdh_server.c.s

modules/asym/src/mbedtls_gen_dh.o: modules/asym/src/mbedtls_gen_dh.c.o
.PHONY : modules/asym/src/mbedtls_gen_dh.o

# target to build an object file
modules/asym/src/mbedtls_gen_dh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_gen_dh.c.o
.PHONY : modules/asym/src/mbedtls_gen_dh.c.o

modules/asym/src/mbedtls_gen_dh.i: modules/asym/src/mbedtls_gen_dh.c.i
.PHONY : modules/asym/src/mbedtls_gen_dh.i

# target to preprocess a source file
modules/asym/src/mbedtls_gen_dh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_gen_dh.c.i
.PHONY : modules/asym/src/mbedtls_gen_dh.c.i

modules/asym/src/mbedtls_gen_dh.s: modules/asym/src/mbedtls_gen_dh.c.s
.PHONY : modules/asym/src/mbedtls_gen_dh.s

# target to generate assembly for a file
modules/asym/src/mbedtls_gen_dh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_gen_dh.c.s
.PHONY : modules/asym/src/mbedtls_gen_dh.c.s

modules/asym/src/mbedtls_rsa.o: modules/asym/src/mbedtls_rsa.c.o
.PHONY : modules/asym/src/mbedtls_rsa.o

# target to build an object file
modules/asym/src/mbedtls_rsa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_rsa.c.o
.PHONY : modules/asym/src/mbedtls_rsa.c.o

modules/asym/src/mbedtls_rsa.i: modules/asym/src/mbedtls_rsa.c.i
.PHONY : modules/asym/src/mbedtls_rsa.i

# target to preprocess a source file
modules/asym/src/mbedtls_rsa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_rsa.c.i
.PHONY : modules/asym/src/mbedtls_rsa.c.i

modules/asym/src/mbedtls_rsa.s: modules/asym/src/mbedtls_rsa.c.s
.PHONY : modules/asym/src/mbedtls_rsa.s

# target to generate assembly for a file
modules/asym/src/mbedtls_rsa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/mbedtls_rsa.c.s
.PHONY : modules/asym/src/mbedtls_rsa.c.s

modules/asym/src/openssl_dh_client.o: modules/asym/src/openssl_dh_client.c.o
.PHONY : modules/asym/src/openssl_dh_client.o

# target to build an object file
modules/asym/src/openssl_dh_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_client.c.o
.PHONY : modules/asym/src/openssl_dh_client.c.o

modules/asym/src/openssl_dh_client.i: modules/asym/src/openssl_dh_client.c.i
.PHONY : modules/asym/src/openssl_dh_client.i

# target to preprocess a source file
modules/asym/src/openssl_dh_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_client.c.i
.PHONY : modules/asym/src/openssl_dh_client.c.i

modules/asym/src/openssl_dh_client.s: modules/asym/src/openssl_dh_client.c.s
.PHONY : modules/asym/src/openssl_dh_client.s

# target to generate assembly for a file
modules/asym/src/openssl_dh_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_client.c.s
.PHONY : modules/asym/src/openssl_dh_client.c.s

modules/asym/src/openssl_dh_server.o: modules/asym/src/openssl_dh_server.c.o
.PHONY : modules/asym/src/openssl_dh_server.o

# target to build an object file
modules/asym/src/openssl_dh_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_server.c.o
.PHONY : modules/asym/src/openssl_dh_server.c.o

modules/asym/src/openssl_dh_server.i: modules/asym/src/openssl_dh_server.c.i
.PHONY : modules/asym/src/openssl_dh_server.i

# target to preprocess a source file
modules/asym/src/openssl_dh_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_server.c.i
.PHONY : modules/asym/src/openssl_dh_server.c.i

modules/asym/src/openssl_dh_server.s: modules/asym/src/openssl_dh_server.c.s
.PHONY : modules/asym/src/openssl_dh_server.s

# target to generate assembly for a file
modules/asym/src/openssl_dh_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_dh_server.c.s
.PHONY : modules/asym/src/openssl_dh_server.c.s

modules/asym/src/openssl_ecc.o: modules/asym/src/openssl_ecc.c.o
.PHONY : modules/asym/src/openssl_ecc.o

# target to build an object file
modules/asym/src/openssl_ecc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_ecc.c.o
.PHONY : modules/asym/src/openssl_ecc.c.o

modules/asym/src/openssl_ecc.i: modules/asym/src/openssl_ecc.c.i
.PHONY : modules/asym/src/openssl_ecc.i

# target to preprocess a source file
modules/asym/src/openssl_ecc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_ecc.c.i
.PHONY : modules/asym/src/openssl_ecc.c.i

modules/asym/src/openssl_ecc.s: modules/asym/src/openssl_ecc.c.s
.PHONY : modules/asym/src/openssl_ecc.s

# target to generate assembly for a file
modules/asym/src/openssl_ecc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_ecc.c.s
.PHONY : modules/asym/src/openssl_ecc.c.s

modules/asym/src/openssl_gen_dh.o: modules/asym/src/openssl_gen_dh.c.o
.PHONY : modules/asym/src/openssl_gen_dh.o

# target to build an object file
modules/asym/src/openssl_gen_dh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_gen_dh.c.o
.PHONY : modules/asym/src/openssl_gen_dh.c.o

modules/asym/src/openssl_gen_dh.i: modules/asym/src/openssl_gen_dh.c.i
.PHONY : modules/asym/src/openssl_gen_dh.i

# target to preprocess a source file
modules/asym/src/openssl_gen_dh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_gen_dh.c.i
.PHONY : modules/asym/src/openssl_gen_dh.c.i

modules/asym/src/openssl_gen_dh.s: modules/asym/src/openssl_gen_dh.c.s
.PHONY : modules/asym/src/openssl_gen_dh.s

# target to generate assembly for a file
modules/asym/src/openssl_gen_dh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_gen_dh.c.s
.PHONY : modules/asym/src/openssl_gen_dh.c.s

modules/asym/src/openssl_rsa.o: modules/asym/src/openssl_rsa.c.o
.PHONY : modules/asym/src/openssl_rsa.o

# target to build an object file
modules/asym/src/openssl_rsa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_rsa.c.o
.PHONY : modules/asym/src/openssl_rsa.c.o

modules/asym/src/openssl_rsa.i: modules/asym/src/openssl_rsa.c.i
.PHONY : modules/asym/src/openssl_rsa.i

# target to preprocess a source file
modules/asym/src/openssl_rsa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_rsa.c.i
.PHONY : modules/asym/src/openssl_rsa.c.i

modules/asym/src/openssl_rsa.s: modules/asym/src/openssl_rsa.c.s
.PHONY : modules/asym/src/openssl_rsa.s

# target to generate assembly for a file
modules/asym/src/openssl_rsa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/asym/src/openssl_rsa.c.s
.PHONY : modules/asym/src/openssl_rsa.c.s

modules/cert/src/mbedtls_cert_crt.o: modules/cert/src/mbedtls_cert_crt.c.o
.PHONY : modules/cert/src/mbedtls_cert_crt.o

# target to build an object file
modules/cert/src/mbedtls_cert_crt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_crt.c.o
.PHONY : modules/cert/src/mbedtls_cert_crt.c.o

modules/cert/src/mbedtls_cert_crt.i: modules/cert/src/mbedtls_cert_crt.c.i
.PHONY : modules/cert/src/mbedtls_cert_crt.i

# target to preprocess a source file
modules/cert/src/mbedtls_cert_crt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_crt.c.i
.PHONY : modules/cert/src/mbedtls_cert_crt.c.i

modules/cert/src/mbedtls_cert_crt.s: modules/cert/src/mbedtls_cert_crt.c.s
.PHONY : modules/cert/src/mbedtls_cert_crt.s

# target to generate assembly for a file
modules/cert/src/mbedtls_cert_crt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_crt.c.s
.PHONY : modules/cert/src/mbedtls_cert_crt.c.s

modules/cert/src/mbedtls_cert_csr.o: modules/cert/src/mbedtls_cert_csr.c.o
.PHONY : modules/cert/src/mbedtls_cert_csr.o

# target to build an object file
modules/cert/src/mbedtls_cert_csr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_csr.c.o
.PHONY : modules/cert/src/mbedtls_cert_csr.c.o

modules/cert/src/mbedtls_cert_csr.i: modules/cert/src/mbedtls_cert_csr.c.i
.PHONY : modules/cert/src/mbedtls_cert_csr.i

# target to preprocess a source file
modules/cert/src/mbedtls_cert_csr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_csr.c.i
.PHONY : modules/cert/src/mbedtls_cert_csr.c.i

modules/cert/src/mbedtls_cert_csr.s: modules/cert/src/mbedtls_cert_csr.c.s
.PHONY : modules/cert/src/mbedtls_cert_csr.s

# target to generate assembly for a file
modules/cert/src/mbedtls_cert_csr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/cert/src/mbedtls_cert_csr.c.s
.PHONY : modules/cert/src/mbedtls_cert_csr.c.s

modules/common/src/mbedtls_common.o: modules/common/src/mbedtls_common.c.o
.PHONY : modules/common/src/mbedtls_common.o

# target to build an object file
modules/common/src/mbedtls_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/mbedtls_common.c.o
.PHONY : modules/common/src/mbedtls_common.c.o

modules/common/src/mbedtls_common.i: modules/common/src/mbedtls_common.c.i
.PHONY : modules/common/src/mbedtls_common.i

# target to preprocess a source file
modules/common/src/mbedtls_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/mbedtls_common.c.i
.PHONY : modules/common/src/mbedtls_common.c.i

modules/common/src/mbedtls_common.s: modules/common/src/mbedtls_common.c.s
.PHONY : modules/common/src/mbedtls_common.s

# target to generate assembly for a file
modules/common/src/mbedtls_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/mbedtls_common.c.s
.PHONY : modules/common/src/mbedtls_common.c.s

modules/common/src/openssl_common.o: modules/common/src/openssl_common.c.o
.PHONY : modules/common/src/openssl_common.o

# target to build an object file
modules/common/src/openssl_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/openssl_common.c.o
.PHONY : modules/common/src/openssl_common.c.o

modules/common/src/openssl_common.i: modules/common/src/openssl_common.c.i
.PHONY : modules/common/src/openssl_common.i

# target to preprocess a source file
modules/common/src/openssl_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/openssl_common.c.i
.PHONY : modules/common/src/openssl_common.c.i

modules/common/src/openssl_common.s: modules/common/src/openssl_common.c.s
.PHONY : modules/common/src/openssl_common.s

# target to generate assembly for a file
modules/common/src/openssl_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/common/src/openssl_common.c.s
.PHONY : modules/common/src/openssl_common.c.s

modules/digest/src/mbedtls_cmac_exa.o: modules/digest/src/mbedtls_cmac_exa.c.o
.PHONY : modules/digest/src/mbedtls_cmac_exa.o

# target to build an object file
modules/digest/src/mbedtls_cmac_exa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_cmac_exa.c.o
.PHONY : modules/digest/src/mbedtls_cmac_exa.c.o

modules/digest/src/mbedtls_cmac_exa.i: modules/digest/src/mbedtls_cmac_exa.c.i
.PHONY : modules/digest/src/mbedtls_cmac_exa.i

# target to preprocess a source file
modules/digest/src/mbedtls_cmac_exa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_cmac_exa.c.i
.PHONY : modules/digest/src/mbedtls_cmac_exa.c.i

modules/digest/src/mbedtls_cmac_exa.s: modules/digest/src/mbedtls_cmac_exa.c.s
.PHONY : modules/digest/src/mbedtls_cmac_exa.s

# target to generate assembly for a file
modules/digest/src/mbedtls_cmac_exa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_cmac_exa.c.s
.PHONY : modules/digest/src/mbedtls_cmac_exa.c.s

modules/digest/src/mbedtls_hmac.o: modules/digest/src/mbedtls_hmac.c.o
.PHONY : modules/digest/src/mbedtls_hmac.o

# target to build an object file
modules/digest/src/mbedtls_hmac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_hmac.c.o
.PHONY : modules/digest/src/mbedtls_hmac.c.o

modules/digest/src/mbedtls_hmac.i: modules/digest/src/mbedtls_hmac.c.i
.PHONY : modules/digest/src/mbedtls_hmac.i

# target to preprocess a source file
modules/digest/src/mbedtls_hmac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_hmac.c.i
.PHONY : modules/digest/src/mbedtls_hmac.c.i

modules/digest/src/mbedtls_hmac.s: modules/digest/src/mbedtls_hmac.c.s
.PHONY : modules/digest/src/mbedtls_hmac.s

# target to generate assembly for a file
modules/digest/src/mbedtls_hmac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_hmac.c.s
.PHONY : modules/digest/src/mbedtls_hmac.c.s

modules/digest/src/mbedtls_md_sha.o: modules/digest/src/mbedtls_md_sha.c.o
.PHONY : modules/digest/src/mbedtls_md_sha.o

# target to build an object file
modules/digest/src/mbedtls_md_sha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_md_sha.c.o
.PHONY : modules/digest/src/mbedtls_md_sha.c.o

modules/digest/src/mbedtls_md_sha.i: modules/digest/src/mbedtls_md_sha.c.i
.PHONY : modules/digest/src/mbedtls_md_sha.i

# target to preprocess a source file
modules/digest/src/mbedtls_md_sha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_md_sha.c.i
.PHONY : modules/digest/src/mbedtls_md_sha.c.i

modules/digest/src/mbedtls_md_sha.s: modules/digest/src/mbedtls_md_sha.c.s
.PHONY : modules/digest/src/mbedtls_md_sha.s

# target to generate assembly for a file
modules/digest/src/mbedtls_md_sha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/mbedtls_md_sha.c.s
.PHONY : modules/digest/src/mbedtls_md_sha.c.s

modules/digest/src/openssl_md_sha.o: modules/digest/src/openssl_md_sha.c.o
.PHONY : modules/digest/src/openssl_md_sha.o

# target to build an object file
modules/digest/src/openssl_md_sha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/openssl_md_sha.c.o
.PHONY : modules/digest/src/openssl_md_sha.c.o

modules/digest/src/openssl_md_sha.i: modules/digest/src/openssl_md_sha.c.i
.PHONY : modules/digest/src/openssl_md_sha.i

# target to preprocess a source file
modules/digest/src/openssl_md_sha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/openssl_md_sha.c.i
.PHONY : modules/digest/src/openssl_md_sha.c.i

modules/digest/src/openssl_md_sha.s: modules/digest/src/openssl_md_sha.c.s
.PHONY : modules/digest/src/openssl_md_sha.s

# target to generate assembly for a file
modules/digest/src/openssl_md_sha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/digest/src/openssl_md_sha.c.s
.PHONY : modules/digest/src/openssl_md_sha.c.s

modules/random/src/mbedtls_random.o: modules/random/src/mbedtls_random.c.o
.PHONY : modules/random/src/mbedtls_random.o

# target to build an object file
modules/random/src/mbedtls_random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/random/src/mbedtls_random.c.o
.PHONY : modules/random/src/mbedtls_random.c.o

modules/random/src/mbedtls_random.i: modules/random/src/mbedtls_random.c.i
.PHONY : modules/random/src/mbedtls_random.i

# target to preprocess a source file
modules/random/src/mbedtls_random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/random/src/mbedtls_random.c.i
.PHONY : modules/random/src/mbedtls_random.c.i

modules/random/src/mbedtls_random.s: modules/random/src/mbedtls_random.c.s
.PHONY : modules/random/src/mbedtls_random.s

# target to generate assembly for a file
modules/random/src/mbedtls_random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/random/src/mbedtls_random.c.s
.PHONY : modules/random/src/mbedtls_random.c.s

modules/sym/src/example_aes.o: modules/sym/src/example_aes.c.o
.PHONY : modules/sym/src/example_aes.o

# target to build an object file
modules/sym/src/example_aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/example_aes.c.o
.PHONY : modules/sym/src/example_aes.c.o

modules/sym/src/example_aes.i: modules/sym/src/example_aes.c.i
.PHONY : modules/sym/src/example_aes.i

# target to preprocess a source file
modules/sym/src/example_aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/example_aes.c.i
.PHONY : modules/sym/src/example_aes.c.i

modules/sym/src/example_aes.s: modules/sym/src/example_aes.c.s
.PHONY : modules/sym/src/example_aes.s

# target to generate assembly for a file
modules/sym/src/example_aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/example_aes.c.s
.PHONY : modules/sym/src/example_aes.c.s

modules/sym/src/mbedtls_sca.o: modules/sym/src/mbedtls_sca.c.o
.PHONY : modules/sym/src/mbedtls_sca.o

# target to build an object file
modules/sym/src/mbedtls_sca.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/mbedtls_sca.c.o
.PHONY : modules/sym/src/mbedtls_sca.c.o

modules/sym/src/mbedtls_sca.i: modules/sym/src/mbedtls_sca.c.i
.PHONY : modules/sym/src/mbedtls_sca.i

# target to preprocess a source file
modules/sym/src/mbedtls_sca.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/mbedtls_sca.c.i
.PHONY : modules/sym/src/mbedtls_sca.c.i

modules/sym/src/mbedtls_sca.s: modules/sym/src/mbedtls_sca.c.s
.PHONY : modules/sym/src/mbedtls_sca.s

# target to generate assembly for a file
modules/sym/src/mbedtls_sca.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/mbedtls_sca.c.s
.PHONY : modules/sym/src/mbedtls_sca.c.s

modules/sym/src/openssl_sca.o: modules/sym/src/openssl_sca.c.o
.PHONY : modules/sym/src/openssl_sca.o

# target to build an object file
modules/sym/src/openssl_sca.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sca.c.o
.PHONY : modules/sym/src/openssl_sca.c.o

modules/sym/src/openssl_sca.i: modules/sym/src/openssl_sca.c.i
.PHONY : modules/sym/src/openssl_sca.i

# target to preprocess a source file
modules/sym/src/openssl_sca.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sca.c.i
.PHONY : modules/sym/src/openssl_sca.c.i

modules/sym/src/openssl_sca.s: modules/sym/src/openssl_sca.c.s
.PHONY : modules/sym/src/openssl_sca.s

# target to generate assembly for a file
modules/sym/src/openssl_sca.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sca.c.s
.PHONY : modules/sym/src/openssl_sca.c.s

modules/sym/src/openssl_sm2.o: modules/sym/src/openssl_sm2.c.o
.PHONY : modules/sym/src/openssl_sm2.o

# target to build an object file
modules/sym/src/openssl_sm2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sm2.c.o
.PHONY : modules/sym/src/openssl_sm2.c.o

modules/sym/src/openssl_sm2.i: modules/sym/src/openssl_sm2.c.i
.PHONY : modules/sym/src/openssl_sm2.i

# target to preprocess a source file
modules/sym/src/openssl_sm2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sm2.c.i
.PHONY : modules/sym/src/openssl_sm2.c.i

modules/sym/src/openssl_sm2.s: modules/sym/src/openssl_sm2.c.s
.PHONY : modules/sym/src/openssl_sm2.s

# target to generate assembly for a file
modules/sym/src/openssl_sm2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/modules/sym/src/openssl_sm2.c.s
.PHONY : modules/sym/src/openssl_sm2.c.s

testsuite/main.o: testsuite/main.c.o
.PHONY : testsuite/main.o

# target to build an object file
testsuite/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/main.c.o
.PHONY : testsuite/main.c.o

testsuite/main.i: testsuite/main.c.i
.PHONY : testsuite/main.i

# target to preprocess a source file
testsuite/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/main.c.i
.PHONY : testsuite/main.c.i

testsuite/main.s: testsuite/main.c.s
.PHONY : testsuite/main.s

# target to generate assembly for a file
testsuite/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/main.c.s
.PHONY : testsuite/main.c.s

testsuite/src/ExampleTestMain.o: testsuite/src/ExampleTestMain.c.o
.PHONY : testsuite/src/ExampleTestMain.o

# target to build an object file
testsuite/src/ExampleTestMain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTestMain.c.o
.PHONY : testsuite/src/ExampleTestMain.c.o

testsuite/src/ExampleTestMain.i: testsuite/src/ExampleTestMain.c.i
.PHONY : testsuite/src/ExampleTestMain.i

# target to preprocess a source file
testsuite/src/ExampleTestMain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTestMain.c.i
.PHONY : testsuite/src/ExampleTestMain.c.i

testsuite/src/ExampleTestMain.s: testsuite/src/ExampleTestMain.c.s
.PHONY : testsuite/src/ExampleTestMain.s

# target to generate assembly for a file
testsuite/src/ExampleTestMain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTestMain.c.s
.PHONY : testsuite/src/ExampleTestMain.c.s

testsuite/src/ExampleTests.o: testsuite/src/ExampleTests.c.o
.PHONY : testsuite/src/ExampleTests.o

# target to build an object file
testsuite/src/ExampleTests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTests.c.o
.PHONY : testsuite/src/ExampleTests.c.o

testsuite/src/ExampleTests.i: testsuite/src/ExampleTests.c.i
.PHONY : testsuite/src/ExampleTests.i

# target to preprocess a source file
testsuite/src/ExampleTests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTests.c.i
.PHONY : testsuite/src/ExampleTests.c.i

testsuite/src/ExampleTests.s: testsuite/src/ExampleTests.c.s
.PHONY : testsuite/src/ExampleTests.s

# target to generate assembly for a file
testsuite/src/ExampleTests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/ExampleTests.c.s
.PHONY : testsuite/src/ExampleTests.c.s

testsuite/src/OpensslTests.o: testsuite/src/OpensslTests.c.o
.PHONY : testsuite/src/OpensslTests.o

# target to build an object file
testsuite/src/OpensslTests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/OpensslTests.c.o
.PHONY : testsuite/src/OpensslTests.c.o

testsuite/src/OpensslTests.i: testsuite/src/OpensslTests.c.i
.PHONY : testsuite/src/OpensslTests.i

# target to preprocess a source file
testsuite/src/OpensslTests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/OpensslTests.c.i
.PHONY : testsuite/src/OpensslTests.c.i

testsuite/src/OpensslTests.s: testsuite/src/OpensslTests.c.s
.PHONY : testsuite/src/OpensslTests.s

# target to generate assembly for a file
testsuite/src/OpensslTests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/OpensslTests.c.s
.PHONY : testsuite/src/OpensslTests.c.s

testsuite/src/unit_test.o: testsuite/src/unit_test.c.o
.PHONY : testsuite/src/unit_test.o

# target to build an object file
testsuite/src/unit_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test.c.o
.PHONY : testsuite/src/unit_test.c.o

testsuite/src/unit_test.i: testsuite/src/unit_test.c.i
.PHONY : testsuite/src/unit_test.i

# target to preprocess a source file
testsuite/src/unit_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test.c.i
.PHONY : testsuite/src/unit_test.c.i

testsuite/src/unit_test.s: testsuite/src/unit_test.c.s
.PHONY : testsuite/src/unit_test.s

# target to generate assembly for a file
testsuite/src/unit_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test.c.s
.PHONY : testsuite/src/unit_test.c.s

testsuite/src/unit_test_mbedtls.o: testsuite/src/unit_test_mbedtls.c.o
.PHONY : testsuite/src/unit_test_mbedtls.o

# target to build an object file
testsuite/src/unit_test_mbedtls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test_mbedtls.c.o
.PHONY : testsuite/src/unit_test_mbedtls.c.o

testsuite/src/unit_test_mbedtls.i: testsuite/src/unit_test_mbedtls.c.i
.PHONY : testsuite/src/unit_test_mbedtls.i

# target to preprocess a source file
testsuite/src/unit_test_mbedtls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test_mbedtls.c.i
.PHONY : testsuite/src/unit_test_mbedtls.c.i

testsuite/src/unit_test_mbedtls.s: testsuite/src/unit_test_mbedtls.c.s
.PHONY : testsuite/src/unit_test_mbedtls.s

# target to generate assembly for a file
testsuite/src/unit_test_mbedtls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/src/unit_test_mbedtls.c.s
.PHONY : testsuite/src/unit_test_mbedtls.c.s

testsuite/thirdpart/src/Basic.o: testsuite/thirdpart/src/Basic.c.o
.PHONY : testsuite/thirdpart/src/Basic.o

# target to build an object file
testsuite/thirdpart/src/Basic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Basic.c.o
.PHONY : testsuite/thirdpart/src/Basic.c.o

testsuite/thirdpart/src/Basic.i: testsuite/thirdpart/src/Basic.c.i
.PHONY : testsuite/thirdpart/src/Basic.i

# target to preprocess a source file
testsuite/thirdpart/src/Basic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Basic.c.i
.PHONY : testsuite/thirdpart/src/Basic.c.i

testsuite/thirdpart/src/Basic.s: testsuite/thirdpart/src/Basic.c.s
.PHONY : testsuite/thirdpart/src/Basic.s

# target to generate assembly for a file
testsuite/thirdpart/src/Basic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Basic.c.s
.PHONY : testsuite/thirdpart/src/Basic.c.s

testsuite/thirdpart/src/CUError.o: testsuite/thirdpart/src/CUError.c.o
.PHONY : testsuite/thirdpart/src/CUError.o

# target to build an object file
testsuite/thirdpart/src/CUError.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/CUError.c.o
.PHONY : testsuite/thirdpart/src/CUError.c.o

testsuite/thirdpart/src/CUError.i: testsuite/thirdpart/src/CUError.c.i
.PHONY : testsuite/thirdpart/src/CUError.i

# target to preprocess a source file
testsuite/thirdpart/src/CUError.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/CUError.c.i
.PHONY : testsuite/thirdpart/src/CUError.c.i

testsuite/thirdpart/src/CUError.s: testsuite/thirdpart/src/CUError.c.s
.PHONY : testsuite/thirdpart/src/CUError.s

# target to generate assembly for a file
testsuite/thirdpart/src/CUError.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/CUError.c.s
.PHONY : testsuite/thirdpart/src/CUError.c.s

testsuite/thirdpart/src/MyMem.o: testsuite/thirdpart/src/MyMem.c.o
.PHONY : testsuite/thirdpart/src/MyMem.o

# target to build an object file
testsuite/thirdpart/src/MyMem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/MyMem.c.o
.PHONY : testsuite/thirdpart/src/MyMem.c.o

testsuite/thirdpart/src/MyMem.i: testsuite/thirdpart/src/MyMem.c.i
.PHONY : testsuite/thirdpart/src/MyMem.i

# target to preprocess a source file
testsuite/thirdpart/src/MyMem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/MyMem.c.i
.PHONY : testsuite/thirdpart/src/MyMem.c.i

testsuite/thirdpart/src/MyMem.s: testsuite/thirdpart/src/MyMem.c.s
.PHONY : testsuite/thirdpart/src/MyMem.s

# target to generate assembly for a file
testsuite/thirdpart/src/MyMem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/MyMem.c.s
.PHONY : testsuite/thirdpart/src/MyMem.c.s

testsuite/thirdpart/src/TestDB.o: testsuite/thirdpart/src/TestDB.c.o
.PHONY : testsuite/thirdpart/src/TestDB.o

# target to build an object file
testsuite/thirdpart/src/TestDB.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestDB.c.o
.PHONY : testsuite/thirdpart/src/TestDB.c.o

testsuite/thirdpart/src/TestDB.i: testsuite/thirdpart/src/TestDB.c.i
.PHONY : testsuite/thirdpart/src/TestDB.i

# target to preprocess a source file
testsuite/thirdpart/src/TestDB.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestDB.c.i
.PHONY : testsuite/thirdpart/src/TestDB.c.i

testsuite/thirdpart/src/TestDB.s: testsuite/thirdpart/src/TestDB.c.s
.PHONY : testsuite/thirdpart/src/TestDB.s

# target to generate assembly for a file
testsuite/thirdpart/src/TestDB.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestDB.c.s
.PHONY : testsuite/thirdpart/src/TestDB.c.s

testsuite/thirdpart/src/TestRun.o: testsuite/thirdpart/src/TestRun.c.o
.PHONY : testsuite/thirdpart/src/TestRun.o

# target to build an object file
testsuite/thirdpart/src/TestRun.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestRun.c.o
.PHONY : testsuite/thirdpart/src/TestRun.c.o

testsuite/thirdpart/src/TestRun.i: testsuite/thirdpart/src/TestRun.c.i
.PHONY : testsuite/thirdpart/src/TestRun.i

# target to preprocess a source file
testsuite/thirdpart/src/TestRun.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestRun.c.i
.PHONY : testsuite/thirdpart/src/TestRun.c.i

testsuite/thirdpart/src/TestRun.s: testsuite/thirdpart/src/TestRun.c.s
.PHONY : testsuite/thirdpart/src/TestRun.s

# target to generate assembly for a file
testsuite/thirdpart/src/TestRun.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/TestRun.c.s
.PHONY : testsuite/thirdpart/src/TestRun.c.s

testsuite/thirdpart/src/Util.o: testsuite/thirdpart/src/Util.c.o
.PHONY : testsuite/thirdpart/src/Util.o

# target to build an object file
testsuite/thirdpart/src/Util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Util.c.o
.PHONY : testsuite/thirdpart/src/Util.c.o

testsuite/thirdpart/src/Util.i: testsuite/thirdpart/src/Util.c.i
.PHONY : testsuite/thirdpart/src/Util.i

# target to preprocess a source file
testsuite/thirdpart/src/Util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Util.c.i
.PHONY : testsuite/thirdpart/src/Util.c.i

testsuite/thirdpart/src/Util.s: testsuite/thirdpart/src/Util.c.s
.PHONY : testsuite/thirdpart/src/Util.s

# target to generate assembly for a file
testsuite/thirdpart/src/Util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/testsuite/thirdpart/src/Util.c.s
.PHONY : testsuite/thirdpart/src/Util.c.s

utils/src/utils.o: utils/src/utils.c.o
.PHONY : utils/src/utils.o

# target to build an object file
utils/src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils.c.o
.PHONY : utils/src/utils.c.o

utils/src/utils.i: utils/src/utils.c.i
.PHONY : utils/src/utils.i

# target to preprocess a source file
utils/src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils.c.i
.PHONY : utils/src/utils.c.i

utils/src/utils.s: utils/src/utils.c.s
.PHONY : utils/src/utils.s

# target to generate assembly for a file
utils/src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils.c.s
.PHONY : utils/src/utils.c.s

utils/src/utils_net_client.o: utils/src/utils_net_client.c.o
.PHONY : utils/src/utils_net_client.o

# target to build an object file
utils/src/utils_net_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_client.c.o
.PHONY : utils/src/utils_net_client.c.o

utils/src/utils_net_client.i: utils/src/utils_net_client.c.i
.PHONY : utils/src/utils_net_client.i

# target to preprocess a source file
utils/src/utils_net_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_client.c.i
.PHONY : utils/src/utils_net_client.c.i

utils/src/utils_net_client.s: utils/src/utils_net_client.c.s
.PHONY : utils/src/utils_net_client.s

# target to generate assembly for a file
utils/src/utils_net_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_client.c.s
.PHONY : utils/src/utils_net_client.c.s

utils/src/utils_net_server.o: utils/src/utils_net_server.c.o
.PHONY : utils/src/utils_net_server.o

# target to build an object file
utils/src/utils_net_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_server.c.o
.PHONY : utils/src/utils_net_server.c.o

utils/src/utils_net_server.i: utils/src/utils_net_server.c.i
.PHONY : utils/src/utils_net_server.i

# target to preprocess a source file
utils/src/utils_net_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_server.c.i
.PHONY : utils/src/utils_net_server.c.i

utils/src/utils_net_server.s: utils/src/utils_net_server.c.s
.PHONY : utils/src/utils_net_server.s

# target to generate assembly for a file
utils/src/utils_net_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_test_entry.elf.dir/build.make CMakeFiles/crypto_test_entry.elf.dir/utils/src/utils_net_server.c.s
.PHONY : utils/src/utils_net_server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crypto_test_entry.elf"
	@echo "... lib/kasumi/f8.o"
	@echo "... lib/kasumi/f8.i"
	@echo "... lib/kasumi/f8.s"
	@echo "... lib/kasumi/f9.o"
	@echo "... lib/kasumi/f9.i"
	@echo "... lib/kasumi/f9.s"
	@echo "... lib/kasumi/kasumi.o"
	@echo "... lib/kasumi/kasumi.i"
	@echo "... lib/kasumi/kasumi.s"
	@echo "... lib/kasumi/test_kasumi.o"
	@echo "... lib/kasumi/test_kasumi.i"
	@echo "... lib/kasumi/test_kasumi.s"
	@echo "... modules/asym/src/mbedtls_dh_client.o"
	@echo "... modules/asym/src/mbedtls_dh_client.i"
	@echo "... modules/asym/src/mbedtls_dh_client.s"
	@echo "... modules/asym/src/mbedtls_dh_server.o"
	@echo "... modules/asym/src/mbedtls_dh_server.i"
	@echo "... modules/asym/src/mbedtls_dh_server.s"
	@echo "... modules/asym/src/mbedtls_ecc.o"
	@echo "... modules/asym/src/mbedtls_ecc.i"
	@echo "... modules/asym/src/mbedtls_ecc.s"
	@echo "... modules/asym/src/mbedtls_ecdh_client.o"
	@echo "... modules/asym/src/mbedtls_ecdh_client.i"
	@echo "... modules/asym/src/mbedtls_ecdh_client.s"
	@echo "... modules/asym/src/mbedtls_ecdh_server.o"
	@echo "... modules/asym/src/mbedtls_ecdh_server.i"
	@echo "... modules/asym/src/mbedtls_ecdh_server.s"
	@echo "... modules/asym/src/mbedtls_gen_dh.o"
	@echo "... modules/asym/src/mbedtls_gen_dh.i"
	@echo "... modules/asym/src/mbedtls_gen_dh.s"
	@echo "... modules/asym/src/mbedtls_rsa.o"
	@echo "... modules/asym/src/mbedtls_rsa.i"
	@echo "... modules/asym/src/mbedtls_rsa.s"
	@echo "... modules/asym/src/openssl_dh_client.o"
	@echo "... modules/asym/src/openssl_dh_client.i"
	@echo "... modules/asym/src/openssl_dh_client.s"
	@echo "... modules/asym/src/openssl_dh_server.o"
	@echo "... modules/asym/src/openssl_dh_server.i"
	@echo "... modules/asym/src/openssl_dh_server.s"
	@echo "... modules/asym/src/openssl_ecc.o"
	@echo "... modules/asym/src/openssl_ecc.i"
	@echo "... modules/asym/src/openssl_ecc.s"
	@echo "... modules/asym/src/openssl_gen_dh.o"
	@echo "... modules/asym/src/openssl_gen_dh.i"
	@echo "... modules/asym/src/openssl_gen_dh.s"
	@echo "... modules/asym/src/openssl_rsa.o"
	@echo "... modules/asym/src/openssl_rsa.i"
	@echo "... modules/asym/src/openssl_rsa.s"
	@echo "... modules/cert/src/mbedtls_cert_crt.o"
	@echo "... modules/cert/src/mbedtls_cert_crt.i"
	@echo "... modules/cert/src/mbedtls_cert_crt.s"
	@echo "... modules/cert/src/mbedtls_cert_csr.o"
	@echo "... modules/cert/src/mbedtls_cert_csr.i"
	@echo "... modules/cert/src/mbedtls_cert_csr.s"
	@echo "... modules/common/src/mbedtls_common.o"
	@echo "... modules/common/src/mbedtls_common.i"
	@echo "... modules/common/src/mbedtls_common.s"
	@echo "... modules/common/src/openssl_common.o"
	@echo "... modules/common/src/openssl_common.i"
	@echo "... modules/common/src/openssl_common.s"
	@echo "... modules/digest/src/mbedtls_cmac_exa.o"
	@echo "... modules/digest/src/mbedtls_cmac_exa.i"
	@echo "... modules/digest/src/mbedtls_cmac_exa.s"
	@echo "... modules/digest/src/mbedtls_hmac.o"
	@echo "... modules/digest/src/mbedtls_hmac.i"
	@echo "... modules/digest/src/mbedtls_hmac.s"
	@echo "... modules/digest/src/mbedtls_md_sha.o"
	@echo "... modules/digest/src/mbedtls_md_sha.i"
	@echo "... modules/digest/src/mbedtls_md_sha.s"
	@echo "... modules/digest/src/openssl_md_sha.o"
	@echo "... modules/digest/src/openssl_md_sha.i"
	@echo "... modules/digest/src/openssl_md_sha.s"
	@echo "... modules/random/src/mbedtls_random.o"
	@echo "... modules/random/src/mbedtls_random.i"
	@echo "... modules/random/src/mbedtls_random.s"
	@echo "... modules/sym/src/example_aes.o"
	@echo "... modules/sym/src/example_aes.i"
	@echo "... modules/sym/src/example_aes.s"
	@echo "... modules/sym/src/mbedtls_sca.o"
	@echo "... modules/sym/src/mbedtls_sca.i"
	@echo "... modules/sym/src/mbedtls_sca.s"
	@echo "... modules/sym/src/openssl_sca.o"
	@echo "... modules/sym/src/openssl_sca.i"
	@echo "... modules/sym/src/openssl_sca.s"
	@echo "... modules/sym/src/openssl_sm2.o"
	@echo "... modules/sym/src/openssl_sm2.i"
	@echo "... modules/sym/src/openssl_sm2.s"
	@echo "... testsuite/main.o"
	@echo "... testsuite/main.i"
	@echo "... testsuite/main.s"
	@echo "... testsuite/src/ExampleTestMain.o"
	@echo "... testsuite/src/ExampleTestMain.i"
	@echo "... testsuite/src/ExampleTestMain.s"
	@echo "... testsuite/src/ExampleTests.o"
	@echo "... testsuite/src/ExampleTests.i"
	@echo "... testsuite/src/ExampleTests.s"
	@echo "... testsuite/src/OpensslTests.o"
	@echo "... testsuite/src/OpensslTests.i"
	@echo "... testsuite/src/OpensslTests.s"
	@echo "... testsuite/src/unit_test.o"
	@echo "... testsuite/src/unit_test.i"
	@echo "... testsuite/src/unit_test.s"
	@echo "... testsuite/src/unit_test_mbedtls.o"
	@echo "... testsuite/src/unit_test_mbedtls.i"
	@echo "... testsuite/src/unit_test_mbedtls.s"
	@echo "... testsuite/thirdpart/src/Basic.o"
	@echo "... testsuite/thirdpart/src/Basic.i"
	@echo "... testsuite/thirdpart/src/Basic.s"
	@echo "... testsuite/thirdpart/src/CUError.o"
	@echo "... testsuite/thirdpart/src/CUError.i"
	@echo "... testsuite/thirdpart/src/CUError.s"
	@echo "... testsuite/thirdpart/src/MyMem.o"
	@echo "... testsuite/thirdpart/src/MyMem.i"
	@echo "... testsuite/thirdpart/src/MyMem.s"
	@echo "... testsuite/thirdpart/src/TestDB.o"
	@echo "... testsuite/thirdpart/src/TestDB.i"
	@echo "... testsuite/thirdpart/src/TestDB.s"
	@echo "... testsuite/thirdpart/src/TestRun.o"
	@echo "... testsuite/thirdpart/src/TestRun.i"
	@echo "... testsuite/thirdpart/src/TestRun.s"
	@echo "... testsuite/thirdpart/src/Util.o"
	@echo "... testsuite/thirdpart/src/Util.i"
	@echo "... testsuite/thirdpart/src/Util.s"
	@echo "... utils/src/utils.o"
	@echo "... utils/src/utils.i"
	@echo "... utils/src/utils.s"
	@echo "... utils/src/utils_net_client.o"
	@echo "... utils/src/utils_net_client.i"
	@echo "... utils/src/utils_net_client.s"
	@echo "... utils/src/utils_net_server.o"
	@echo "... utils/src/utils_net_server.i"
	@echo "... utils/src/utils_net_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

