//
// Created by carlos on 2020/12/15.
//

#ifndef CARLOS_OPENMBED_ERRORS_H
#define CARLOS_OPENMBED_ERRORS_H

typedef enum error_num_t {
    ERROR_NONE = 0,
    ERROR_CRYPTO_NO_ALGO,
    ERROR_CRYPTO_GEN_KEY_FAILED,
    ERROR_CRYPTO_READ_KEY_FAILED,
    ERROR_CRYPTO_ENCRYPT_FAILED,
    ERROR_CRYPTO_DECRYPT_FAILED,
    ERROR_COMMON_INPUT_PARAMETERS,
    ERROR_COMMON_MALLOC_FAILED,
    ERROR_COMMON_BUFFER_INSUFFIENT

} ERROR_NUM;


#endif //CARLOS_OPENMBED_ERRORS_H
